model_list:
  - model_name: glm-4.5
    litellm_params:
      model: openai/glm-4.5
      api_base: "https://open.bigmodel.cn/api/paas/v4"
      api_key: "xxx"


litellm_settings:
  drop_params: true
  set_verbose: false
